<a href="https://colab.research.google.com/github/hl1WBG21/DataScience_Ai/blob/main/lab2_datawrangling_applied_data_science_capstone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# lab2: data wrangling

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/dataset_part_1.csv")

In [4]:
df.head(3)

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857

In [7]:
df.isnull().sum()/len(df)*100

FlightNumber       0.000000
Date               0.000000
BoosterVersion     0.000000
PayloadMass        0.000000
Orbit              0.000000
LaunchSite         0.000000
Outcome            0.000000
Flights            0.000000
GridFins           0.000000
Reused             0.000000
Legs               0.000000
LandingPad        28.888889
Block              0.000000
ReusedCount        0.000000
Serial             0.000000
Longitude          0.000000
Latitude           0.000000
dtype: float64

In [10]:
df.dtypes

FlightNumber        int64
Date               object
BoosterVersion     object
PayloadMass       float64
Orbit              object
LaunchSite         object
Outcome            object
Flights             int64
GridFins             bool
Reused               bool
Legs                 bool
LandingPad         object
Block             float64
ReusedCount         int64
Serial             object
Longitude         float64
Latitude          float64
dtype: object

In [13]:
df.describe(include='all')

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
count,90.000000,90,90,90.000000,90,90,90,90.000000,90,90,90,64,90.000000,90.000000,90,90.000000,90.000000
unique,NaN,90,1,NaN,11,3,8,NaN,2,2,2,5,NaN,NaN,53,NaN,NaN
top,NaN,2010-06-04,Falcon 9,NaN,GTO,CCAFS SLC 40,True ASDS,NaN,True,False,True,5e9e3032383ecb6bb234e7ca,NaN,NaN,B1049,NaN,NaN
freq,NaN,1,90,NaN,27,55,41,NaN,70,53,71,35,NaN,NaN,6,NaN,NaN
mean,45.500000,NaN,NaN,6104.959412,NaN,NaN,NaN,1.788889,NaN,NaN,NaN,NaN,3.500000,1.655556,NaN,-86.366477,29.449963
std,26.124701,NaN,NaN,4694.671720,NaN,NaN,NaN,1.213172,NaN,NaN,NaN,NaN,1.595288,1.710254,NaN,14.149518,2.141306
min,1.000000,NaN,NaN,350.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,1.000000,0.000000,NaN,-120.610829,28.561857
25%,23.250000,NaN,NaN,2510.750000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,2.000000,0.000000,NaN,-80.603956,28.561857
50%,45.500000,NaN,NaN,4701.500000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,4.000000,1.000000,NaN,-80.577366,28.561857
75%,67.750000,NaN,NaN,8912.750000,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,5.000000,3.000000,NaN,-80.577366,28.608058
max,90.000000,NaN,NaN,15600.000000,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,5.000000,5.000000,NaN,-80.577366,34.632093

In [25]:
pd.value_counts(df.LaunchSite)
#df.LaunchSite.value_counts()

CCAFS SLC 40    55
KSC LC 39A      22
VAFB SLC 4E     13
Name: LaunchSite, dtype: int64

In [22]:
landing_outcomes=df.Outcome.value_counts()
#pd.value_counts(df.Outcome)

In [48]:
landing_outcomes

True ASDS      41
None None      19
True RTLS      14
False ASDS      6
True Ocean      5
False Ocean     2
None ASDS       2
False RTLS      1
Name: Outcome, dtype: int64

In [44]:
for i,outcome in enumerate(landing_outcomes.keys()):
    print(i,outcome[0])

0 T
1 N
2 T
3 F
4 T
5 F
6 N
7 F

In [37]:
bad_outcomes=set(landing_outcomes.keys()[[1,3,5,6,7]])
bad_outcomes

{'False ASDS', 'False Ocean', 'False RTLS', 'None ASDS', 'None None'}

In [68]:
bad_outcomes=[]
for i,outcome in enumerate(landing_outcomes.keys()):
    #print(i,landing_outcomes.keys()[i][0])
    if outcome[0] in ["N","F"] :
      #print(outcome)
      bad_outcomes.append(outcome)

In [72]:
bad_outcomes

['None None', 'False ASDS', 'False Ocean', 'None ASDS', 'False RTLS']

In [94]:
landing_classe_0=[]
for i,outcome in enumerate(landing_outcomes.keys()):
    if outcome in bad_outcomes :
      landing_classe_0.append(0)
    else :
      landing_classe_0.append(1)

In [95]:
landing_classe_0

[1, 0, 1, 0, 1, 0, 0, 0]

In [88]:
landing_classe=[]
for i,outcome in enumerate(df.Outcome) :
  if outcome in bad_outcomes :
    landing_classe.append(0)
  else :
    landing_classe.append(1)

In [91]:
df["classe"]=landing_classe

In [99]:
# the success rate
df["classe"].mean()

0.6666666666666666

In [100]:
df.to_csv("dataset_part_2.csv", index=False)